# Generated by Django 2.2.6 on 2019-11-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=10),
        ),
    ]
